head_tracking_soft_controller:
  type: head_tracking_soft_controller/HeadTrackingSoftController
  joints:
    - head_pan_joint
    - head_tilt_joint

  gains:
    head_pan_joint: {p: 25.0, i: 12.0, d: 2.0, i_clamp: 0.5}
    head_tilt_joint: {p: 100.0, i: 2.0, d: 3.0, i_clamp: 0.1}
