l_arm_soft_controller:
  type: pr2_soft_controller/Pr2SoftController
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint

  gains:
    l_shoulder_pan_joint: {p: 800.0, d: 10.0}
    l_shoulder_lift_joint: {p: 800.0, d: 10.0}
    l_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    l_elbow_flex_joint: {p: 100.0, d: 3.0}
    l_forearm_roll_joint: {p: 500.0, d: 6.0}
    l_wrist_flex_joint: {p: 400.0, d: 4.0}
    l_wrist_roll_joint: {p: 400.0, d: 4.0}

