pr2_soft_controller:
  type: pr2_soft_controller/Pr2SoftController
  joints:
    - torso_lift_joint
    - head_pan_joint
    - head_tilt_joint
    - laser_tilt_mount_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - r_gripper_joint
    - r_gripper_l_finger_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - l_gripper_joint
    - l_gripper_l_finger_joint

  gains:
    torso_lift_joint: {p: 10000000.0, d: 1000000.0}
    head_pan_joint: {p: 25.0, i: 12.0, d: 2.0, i_clamp: 0.5}
    head_tilt_joint: {p: 49.6, i: 2.0, d: 1.6, i_clamp: 0.1}
    laser_tilt_mount_joint: {p: 0.0, d: 0.0}
    r_shoulder_pan_joint: {p: 800.0, d: 10.0}
    r_shoulder_lift_joint: {p: 800.0, d: 10.0}
    r_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    r_elbow_flex_joint: {p: 100.0, d: 3.0}
    r_forearm_roll_joint: {p: 500.0, d: 6.0}
    r_wrist_flex_joint: {p: 400.0, d: 4.0}
    r_wrist_roll_joint: {p: 400.0, d: 4.0}
    r_gripper_joint: {p: 0.0, d: 0.0}
    r_gripper_l_finger_joint: {p: 0.0, d: 0.0}
    l_shoulder_pan_joint: {p: 800.0, d: 10.0}
    l_shoulder_lift_joint: {p: 800.0, d: 10.0}
    l_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    l_elbow_flex_joint: {p: 100.0, d: 3.0}
    l_forearm_roll_joint: {p: 500.0, d: 6.0}
    l_wrist_flex_joint: {p: 400.0, d: 4.0}
    l_wrist_roll_joint: {p: 400.0, d: 4.0}
    l_gripper_joint: {p: 0.0, d: 0.0}
    l_gripper_l_finger_joint: {p: 0.0, d: 0.0}

