r_arm_soft_controller:
  type: pr2_soft_controller/Pr2SoftController
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint

  gains:
    r_shoulder_pan_joint: {p: 800.0, d: 10.0}
    r_shoulder_lift_joint: {p: 800.0, d: 10.0}
    r_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    r_elbow_flex_joint: {p: 100.0, d: 3.0}
    r_forearm_roll_joint: {p: 500.0, d: 6.0}
    r_wrist_flex_joint: {p: 400.0, d: 4.0}
    r_wrist_roll_joint: {p: 400.0, d: 4.0}

