; Auto-generated. Do not edit!


(cl:in-package pr2_soft_controller-msg)


;//! \htmlinclude SM_TRAJ_STR_ROS.msg.html

(cl:defclass <SM_TRAJ_STR_ROS> (roslisp-msg-protocol:ros-message)
  ((trajId
    :reader trajId
    :initarg :trajId
    :type cl:integer
    :initform 0)
   (nbAxis
    :reader nbAxis
    :initarg :nbAxis
    :type cl:integer
    :initform 0)
   (timePreserved
    :reader timePreserved
    :initarg :timePreserved
    :type cl:float
    :initform 0.0)
   (qStart
    :reader qStart
    :initarg :qStart
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (qGoal
    :reader qGoal
    :initarg :qGoal
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (jmax
    :reader jmax
    :initarg :jmax
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (amax
    :reader amax
    :initarg :amax
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (vmax
    :reader vmax
    :initarg :vmax
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (traj
    :reader traj
    :initarg :traj
    :type (cl:vector pr2_soft_controller-msg:SM_TRAJ_AXIS_STR_ROS)
   :initform (cl:make-array 0 :element-type 'pr2_soft_controller-msg:SM_TRAJ_AXIS_STR_ROS :initial-element (cl:make-instance 'pr2_soft_controller-msg:SM_TRAJ_AXIS_STR_ROS))))
)

(cl:defclass SM_TRAJ_STR_ROS (<SM_TRAJ_STR_ROS>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SM_TRAJ_STR_ROS>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SM_TRAJ_STR_ROS)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr2_soft_controller-msg:<SM_TRAJ_STR_ROS> is deprecated: use pr2_soft_controller-msg:SM_TRAJ_STR_ROS instead.")))

(cl:ensure-generic-function 'trajId-val :lambda-list '(m))
(cl:defmethod trajId-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:trajId-val is deprecated.  Use pr2_soft_controller-msg:trajId instead.")
  (trajId m))

(cl:ensure-generic-function 'nbAxis-val :lambda-list '(m))
(cl:defmethod nbAxis-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:nbAxis-val is deprecated.  Use pr2_soft_controller-msg:nbAxis instead.")
  (nbAxis m))

(cl:ensure-generic-function 'timePreserved-val :lambda-list '(m))
(cl:defmethod timePreserved-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:timePreserved-val is deprecated.  Use pr2_soft_controller-msg:timePreserved instead.")
  (timePreserved m))

(cl:ensure-generic-function 'qStart-val :lambda-list '(m))
(cl:defmethod qStart-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:qStart-val is deprecated.  Use pr2_soft_controller-msg:qStart instead.")
  (qStart m))

(cl:ensure-generic-function 'qGoal-val :lambda-list '(m))
(cl:defmethod qGoal-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:qGoal-val is deprecated.  Use pr2_soft_controller-msg:qGoal instead.")
  (qGoal m))

(cl:ensure-generic-function 'jmax-val :lambda-list '(m))
(cl:defmethod jmax-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:jmax-val is deprecated.  Use pr2_soft_controller-msg:jmax instead.")
  (jmax m))

(cl:ensure-generic-function 'amax-val :lambda-list '(m))
(cl:defmethod amax-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:amax-val is deprecated.  Use pr2_soft_controller-msg:amax instead.")
  (amax m))

(cl:ensure-generic-function 'vmax-val :lambda-list '(m))
(cl:defmethod vmax-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:vmax-val is deprecated.  Use pr2_soft_controller-msg:vmax instead.")
  (vmax m))

(cl:ensure-generic-function 'traj-val :lambda-list '(m))
(cl:defmethod traj-val ((m <SM_TRAJ_STR_ROS>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr2_soft_controller-msg:traj-val is deprecated.  Use pr2_soft_controller-msg:traj instead.")
  (traj m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SM_TRAJ_STR_ROS>) ostream)
  "Serializes a message object of type '<SM_TRAJ_STR_ROS>"
  (cl:let* ((signed (cl:slot-value msg 'trajId)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'nbAxis)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'timePreserved))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'qStart))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'qStart))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'qGoal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'qGoal))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'jmax))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'jmax))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'amax))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'amax))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'vmax))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'vmax))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'traj))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'traj))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SM_TRAJ_STR_ROS>) istream)
  "Deserializes a message object of type '<SM_TRAJ_STR_ROS>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'trajId) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'nbAxis) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'timePreserved) (roslisp-utils:decode-double-float-bits bits)))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'qStart) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'qStart)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'qGoal) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'qGoal)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'jmax) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'jmax)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'amax) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'amax)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'vmax) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'vmax)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'traj) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'traj)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'pr2_soft_controller-msg:SM_TRAJ_AXIS_STR_ROS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SM_TRAJ_STR_ROS>)))
  "Returns string type for a message object of type '<SM_TRAJ_STR_ROS>"
  "pr2_soft_controller/SM_TRAJ_STR_ROS")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SM_TRAJ_STR_ROS)))
  "Returns string type for a message object of type 'SM_TRAJ_STR_ROS"
  "pr2_soft_controller/SM_TRAJ_STR_ROS")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SM_TRAJ_STR_ROS>)))
  "Returns md5sum for a message object of type '<SM_TRAJ_STR_ROS>"
  "2c772c1b72e1b0c0587ff0aecfcbcaf1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SM_TRAJ_STR_ROS)))
  "Returns md5sum for a message object of type 'SM_TRAJ_STR_ROS"
  "2c772c1b72e1b0c0587ff0aecfcbcaf1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SM_TRAJ_STR_ROS>)))
  "Returns full string definition for message of type '<SM_TRAJ_STR_ROS>"
  (cl:format cl:nil "int32 trajId~%int32 nbAxis~%float64 timePreserved~%float64[] qStart~%float64[] qGoal~%float64[] jmax~%float64[] amax~%float64[] vmax~%SM_TRAJ_AXIS_STR_ROS[] traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS~%int32 nbSeg~%int32 unsused~%SM_SEGMENT_STR_ROS[] seg~%~%~%================================================================================~%MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS~%int32 lpId~%int32 unused~%float64 timeOnTraj~%float64 time~%float64 ic_a~%float64 ic_v~%float64 ic_x~%float64 jerk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SM_TRAJ_STR_ROS)))
  "Returns full string definition for message of type 'SM_TRAJ_STR_ROS"
  (cl:format cl:nil "int32 trajId~%int32 nbAxis~%float64 timePreserved~%float64[] qStart~%float64[] qGoal~%float64[] jmax~%float64[] amax~%float64[] vmax~%SM_TRAJ_AXIS_STR_ROS[] traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS~%int32 nbSeg~%int32 unsused~%SM_SEGMENT_STR_ROS[] seg~%~%~%================================================================================~%MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS~%int32 lpId~%int32 unused~%float64 timeOnTraj~%float64 time~%float64 ic_a~%float64 ic_v~%float64 ic_x~%float64 jerk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SM_TRAJ_STR_ROS>))
  (cl:+ 0
     4
     4
     8
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'qStart) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'qGoal) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'jmax) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'amax) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'vmax) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'traj) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SM_TRAJ_STR_ROS>))
  "Converts a ROS message object to a list"
  (cl:list 'SM_TRAJ_STR_ROS
    (cl:cons ':trajId (trajId msg))
    (cl:cons ':nbAxis (nbAxis msg))
    (cl:cons ':timePreserved (timePreserved msg))
    (cl:cons ':qStart (qStart msg))
    (cl:cons ':qGoal (qGoal msg))
    (cl:cons ':jmax (jmax msg))
    (cl:cons ':amax (amax msg))
    (cl:cons ':vmax (vmax msg))
    (cl:cons ':traj (traj msg))
))
