"""autogenerated by genmsg_py from SM_TRAJ_AXIS_STR_ROS.msg. Do not edit."""
import roslib.message
import struct

import pr2_soft_controller.msg

class SM_TRAJ_AXIS_STR_ROS(roslib.message.Message):
  _md5sum = "46d28de6583e6d91193c1deecfbc745d"
  _type = "pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 nbSeg
int32 unsused
SM_SEGMENT_STR_ROS[] seg


================================================================================
MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS
int32 lpId
int32 unused
float64 timeOnTraj
float64 time
float64 ic_a
float64 ic_v
float64 ic_x
float64 jerk


"""
  __slots__ = ['nbSeg','unsused','seg']
  _slot_types = ['int32','int32','pr2_soft_controller/SM_SEGMENT_STR_ROS[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       nbSeg,unsused,seg
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SM_TRAJ_AXIS_STR_ROS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nbSeg is None:
        self.nbSeg = 0
      if self.unsused is None:
        self.unsused = 0
      if self.seg is None:
        self.seg = []
    else:
      self.nbSeg = 0
      self.unsused = 0
      self.seg = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.nbSeg, _x.unsused))
      length = len(self.seg)
      buff.write(_struct_I.pack(length))
      for val1 in self.seg:
        _x = val1
        buff.write(_struct_2i6d.pack(_x.lpId, _x.unused, _x.timeOnTraj, _x.time, _x.ic_a, _x.ic_v, _x.ic_x, _x.jerk))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.nbSeg, _x.unsused,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.seg = []
      for i in range(0, length):
        val1 = pr2_soft_controller.msg.SM_SEGMENT_STR_ROS()
        _x = val1
        start = end
        end += 56
        (_x.lpId, _x.unused, _x.timeOnTraj, _x.time, _x.ic_a, _x.ic_v, _x.ic_x, _x.jerk,) = _struct_2i6d.unpack(str[start:end])
        self.seg.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.nbSeg, _x.unsused))
      length = len(self.seg)
      buff.write(_struct_I.pack(length))
      for val1 in self.seg:
        _x = val1
        buff.write(_struct_2i6d.pack(_x.lpId, _x.unused, _x.timeOnTraj, _x.time, _x.ic_a, _x.ic_v, _x.ic_x, _x.jerk))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.nbSeg, _x.unsused,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.seg = []
      for i in range(0, length):
        val1 = pr2_soft_controller.msg.SM_SEGMENT_STR_ROS()
        _x = val1
        start = end
        end += 56
        (_x.lpId, _x.unused, _x.timeOnTraj, _x.time, _x.ic_a, _x.ic_v, _x.ic_x, _x.jerk,) = _struct_2i6d.unpack(str[start:end])
        self.seg.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2i6d = struct.Struct("<2i6d")
_struct_2i = struct.Struct("<2i")
