/* Auto-generated by genmsg_cpp for file /u/gmanfred/ros/release/soft_controllers/soft_move_base/msg/SoftMoveBaseActionGoal.msg */
#ifndef SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEACTIONGOAL_H
#define SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "soft_move_base/SoftMoveBaseGoal.h"

namespace soft_move_base
{
template <class ContainerAllocator>
struct SoftMoveBaseActionGoal_ {
  typedef SoftMoveBaseActionGoal_<ContainerAllocator> Type;

  SoftMoveBaseActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  SoftMoveBaseActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::soft_move_base::SoftMoveBaseGoal_<ContainerAllocator>  _goal_type;
   ::soft_move_base::SoftMoveBaseGoal_<ContainerAllocator>  goal;


private:
  static const char* __s_getDataType_() { return "soft_move_base/SoftMoveBaseActionGoal"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "59208ee2e3dc4e794d85f7b90e9d2097"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
SoftMoveBaseGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: soft_move_base/SoftMoveBaseGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
pr2_soft_controller/SM_TRAJ_STR_ROS traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_STR_ROS\n\
int32 trajId\n\
int32 nbAxis\n\
float64 timePreserved\n\
float64[] qStart\n\
float64[] qGoal\n\
float64[] jmax\n\
float64[] amax\n\
float64[] vmax\n\
SM_TRAJ_AXIS_STR_ROS[] traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS\n\
int32 nbSeg\n\
int32 unsused\n\
SM_SEGMENT_STR_ROS[] seg\n\
\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS\n\
int32 lpId\n\
int32 unused\n\
float64 timeOnTraj\n\
float64 time\n\
float64 ic_a\n\
float64 ic_v\n\
float64 ic_x\n\
float64 jerk\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, goal_id);
    ros::serialization::serialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, goal_id);
    ros::serialization::deserialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(goal_id);
    size += ros::serialization::serializationLength(goal);
    return size;
  }

  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SoftMoveBaseActionGoal
typedef  ::soft_move_base::SoftMoveBaseActionGoal_<std::allocator<void> > SoftMoveBaseActionGoal;

typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseActionGoal> SoftMoveBaseActionGoalPtr;
typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseActionGoal const> SoftMoveBaseActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace soft_move_base

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "59208ee2e3dc4e794d85f7b90e9d2097";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x59208ee2e3dc4e79ULL;
  static const uint64_t static_value2 = 0x4d85f7b90e9d2097ULL;
};

template<class ContainerAllocator>
struct DataType< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "soft_move_base/SoftMoveBaseActionGoal";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
SoftMoveBaseGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: soft_move_base/SoftMoveBaseGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
pr2_soft_controller/SM_TRAJ_STR_ROS traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_STR_ROS\n\
int32 trajId\n\
int32 nbAxis\n\
float64 timePreserved\n\
float64[] qStart\n\
float64[] qGoal\n\
float64[] jmax\n\
float64[] amax\n\
float64[] vmax\n\
SM_TRAJ_AXIS_STR_ROS[] traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS\n\
int32 nbSeg\n\
int32 unsused\n\
SM_SEGMENT_STR_ROS[] seg\n\
\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS\n\
int32 lpId\n\
int32 unused\n\
float64 timeOnTraj\n\
float64 time\n\
float64 ic_a\n\
float64 ic_v\n\
float64 ic_x\n\
float64 jerk\n\
\n\
\n\
";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SoftMoveBaseActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::soft_move_base::SoftMoveBaseActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::soft_move_base::SoftMoveBaseGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEACTIONGOAL_H

