/* Auto-generated by genmsg_cpp for file /u/gmanfred/ros/release/soft_controllers/soft_move_base/msg/SoftMoveBaseResult.msg */
#ifndef SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASERESULT_H
#define SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace soft_move_base
{
template <class ContainerAllocator>
struct SoftMoveBaseResult_ {
  typedef SoftMoveBaseResult_<ContainerAllocator> Type;

  SoftMoveBaseResult_()
  : result(false)
  {
  }

  SoftMoveBaseResult_(const ContainerAllocator& _alloc)
  : result(false)
  {
  }

  typedef uint8_t _result_type;
  uint8_t result;


private:
  static const char* __s_getDataType_() { return "soft_move_base/SoftMoveBaseResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "eb13ac1f1354ccecb7941ee8fa2192e8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool result\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SoftMoveBaseResult
typedef  ::soft_move_base::SoftMoveBaseResult_<std::allocator<void> > SoftMoveBaseResult;

typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseResult> SoftMoveBaseResultPtr;
typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseResult const> SoftMoveBaseResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace soft_move_base

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "soft_move_base/SoftMoveBaseResult";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool result\n\
\n\
";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SoftMoveBaseResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::soft_move_base::SoftMoveBaseResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASERESULT_H

