/* Auto-generated by genmsg_cpp for file /u/gmanfred/ros/release/soft_controllers/soft_move_base/msg/SoftMoveBaseFeedback.msg */
#ifndef SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEFEEDBACK_H
#define SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace soft_move_base
{
template <class ContainerAllocator>
struct SoftMoveBaseFeedback_ {
  typedef SoftMoveBaseFeedback_<ContainerAllocator> Type;

  SoftMoveBaseFeedback_()
  : ntr(false)
  {
  }

  SoftMoveBaseFeedback_(const ContainerAllocator& _alloc)
  : ntr(false)
  {
  }

  typedef uint8_t _ntr_type;
  uint8_t ntr;


private:
  static const char* __s_getDataType_() { return "soft_move_base/SoftMoveBaseFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "efe4204cdf72ddf9398fed4527485fc3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback (nothing to report)\n\
bool ntr\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ntr);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ntr);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ntr);
    return size;
  }

  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SoftMoveBaseFeedback
typedef  ::soft_move_base::SoftMoveBaseFeedback_<std::allocator<void> > SoftMoveBaseFeedback;

typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseFeedback> SoftMoveBaseFeedbackPtr;
typedef boost::shared_ptr< ::soft_move_base::SoftMoveBaseFeedback const> SoftMoveBaseFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace soft_move_base

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efe4204cdf72ddf9398fed4527485fc3";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xefe4204cdf72ddf9ULL;
  static const uint64_t static_value2 = 0x398fed4527485fc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "soft_move_base/SoftMoveBaseFeedback";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback (nothing to report)\n\
bool ntr\n\
\n\
\n\
";
  }

  static const char* value(const  ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ntr);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SoftMoveBaseFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::soft_move_base::SoftMoveBaseFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "ntr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ntr);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOFT_MOVE_BASE_MESSAGE_SOFTMOVEBASEFEEDBACK_H

