(cl:defpackage soft_move_base-msg
  (:use )
  (:export
   "<SOFTMOVEBASEACTIONFEEDBACK>"
   "SOFTMOVEBASEACTIONFEEDBACK"
   "<SOFTMOVEBASEFEEDBACK>"
   "SOFTMOVEBASEFEEDBACK"
   "<SOFTMOVEBASEACTIONRESULT>"
   "SOFTMOVEBASEACTIONRESULT"
   "<SOFTMOVEBASEACTIONGOAL>"
   "SOFTMOVEBASEACTIONGOAL"
   "<SOFTMOVEBASEACTION>"
   "SOFTMOVEBASEACTION"
   "<SOFTMOVEBASEGOAL>"
   "SOFTMOVEBASEGOAL"
   "<SOFTMOVEBASERESULT>"
   "SOFTMOVEBASERESULT"
  ))

