; Auto-generated. Do not edit!


(cl:in-package soft_move_base-msg)


;//! \htmlinclude SoftMoveBaseFeedback.msg.html

(cl:defclass <SoftMoveBaseFeedback> (roslisp-msg-protocol:ros-message)
  ((ntr
    :reader ntr
    :initarg :ntr
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SoftMoveBaseFeedback (<SoftMoveBaseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoftMoveBaseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoftMoveBaseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name soft_move_base-msg:<SoftMoveBaseFeedback> is deprecated: use soft_move_base-msg:SoftMoveBaseFeedback instead.")))

(cl:ensure-generic-function 'ntr-val :lambda-list '(m))
(cl:defmethod ntr-val ((m <SoftMoveBaseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader soft_move_base-msg:ntr-val is deprecated.  Use soft_move_base-msg:ntr instead.")
  (ntr m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoftMoveBaseFeedback>) ostream)
  "Serializes a message object of type '<SoftMoveBaseFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'ntr) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoftMoveBaseFeedback>) istream)
  "Deserializes a message object of type '<SoftMoveBaseFeedback>"
    (cl:setf (cl:slot-value msg 'ntr) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoftMoveBaseFeedback>)))
  "Returns string type for a message object of type '<SoftMoveBaseFeedback>"
  "soft_move_base/SoftMoveBaseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoftMoveBaseFeedback)))
  "Returns string type for a message object of type 'SoftMoveBaseFeedback"
  "soft_move_base/SoftMoveBaseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoftMoveBaseFeedback>)))
  "Returns md5sum for a message object of type '<SoftMoveBaseFeedback>"
  "efe4204cdf72ddf9398fed4527485fc3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoftMoveBaseFeedback)))
  "Returns md5sum for a message object of type 'SoftMoveBaseFeedback"
  "efe4204cdf72ddf9398fed4527485fc3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoftMoveBaseFeedback>)))
  "Returns full string definition for message of type '<SoftMoveBaseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (nothing to report)~%bool ntr~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoftMoveBaseFeedback)))
  "Returns full string definition for message of type 'SoftMoveBaseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (nothing to report)~%bool ntr~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoftMoveBaseFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoftMoveBaseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SoftMoveBaseFeedback
    (cl:cons ':ntr (ntr msg))
))
