; Auto-generated. Do not edit!


(cl:in-package soft_move_base-msg)


;//! \htmlinclude SoftMoveBaseGoal.msg.html

(cl:defclass <SoftMoveBaseGoal> (roslisp-msg-protocol:ros-message)
  ((traj
    :reader traj
    :initarg :traj
    :type pr2_soft_controller-msg:SM_TRAJ_STR_ROS
    :initform (cl:make-instance 'pr2_soft_controller-msg:SM_TRAJ_STR_ROS)))
)

(cl:defclass SoftMoveBaseGoal (<SoftMoveBaseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoftMoveBaseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoftMoveBaseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name soft_move_base-msg:<SoftMoveBaseGoal> is deprecated: use soft_move_base-msg:SoftMoveBaseGoal instead.")))

(cl:ensure-generic-function 'traj-val :lambda-list '(m))
(cl:defmethod traj-val ((m <SoftMoveBaseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader soft_move_base-msg:traj-val is deprecated.  Use soft_move_base-msg:traj instead.")
  (traj m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoftMoveBaseGoal>) ostream)
  "Serializes a message object of type '<SoftMoveBaseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'traj) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoftMoveBaseGoal>) istream)
  "Deserializes a message object of type '<SoftMoveBaseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'traj) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoftMoveBaseGoal>)))
  "Returns string type for a message object of type '<SoftMoveBaseGoal>"
  "soft_move_base/SoftMoveBaseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoftMoveBaseGoal)))
  "Returns string type for a message object of type 'SoftMoveBaseGoal"
  "soft_move_base/SoftMoveBaseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoftMoveBaseGoal>)))
  "Returns md5sum for a message object of type '<SoftMoveBaseGoal>"
  "d5522a248bbf08e0a75f1902c082cf61")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoftMoveBaseGoal)))
  "Returns md5sum for a message object of type 'SoftMoveBaseGoal"
  "d5522a248bbf08e0a75f1902c082cf61")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoftMoveBaseGoal>)))
  "Returns full string definition for message of type '<SoftMoveBaseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%pr2_soft_controller/SM_TRAJ_STR_ROS traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_STR_ROS~%int32 trajId~%int32 nbAxis~%float64 timePreserved~%float64[] qStart~%float64[] qGoal~%float64[] jmax~%float64[] amax~%float64[] vmax~%SM_TRAJ_AXIS_STR_ROS[] traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS~%int32 nbSeg~%int32 unsused~%SM_SEGMENT_STR_ROS[] seg~%~%~%================================================================================~%MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS~%int32 lpId~%int32 unused~%float64 timeOnTraj~%float64 time~%float64 ic_a~%float64 ic_v~%float64 ic_x~%float64 jerk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoftMoveBaseGoal)))
  "Returns full string definition for message of type 'SoftMoveBaseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%pr2_soft_controller/SM_TRAJ_STR_ROS traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_STR_ROS~%int32 trajId~%int32 nbAxis~%float64 timePreserved~%float64[] qStart~%float64[] qGoal~%float64[] jmax~%float64[] amax~%float64[] vmax~%SM_TRAJ_AXIS_STR_ROS[] traj~%~%================================================================================~%MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS~%int32 nbSeg~%int32 unsused~%SM_SEGMENT_STR_ROS[] seg~%~%~%================================================================================~%MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS~%int32 lpId~%int32 unused~%float64 timeOnTraj~%float64 time~%float64 ic_a~%float64 ic_v~%float64 ic_x~%float64 jerk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoftMoveBaseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'traj))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoftMoveBaseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SoftMoveBaseGoal
    (cl:cons ':traj (traj msg))
))
