; Auto-generated. Do not edit!


(cl:in-package soft_move_base-msg)


;//! \htmlinclude SoftMoveBaseResult.msg.html

(cl:defclass <SoftMoveBaseResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SoftMoveBaseResult (<SoftMoveBaseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoftMoveBaseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoftMoveBaseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name soft_move_base-msg:<SoftMoveBaseResult> is deprecated: use soft_move_base-msg:SoftMoveBaseResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <SoftMoveBaseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader soft_move_base-msg:result-val is deprecated.  Use soft_move_base-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoftMoveBaseResult>) ostream)
  "Serializes a message object of type '<SoftMoveBaseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoftMoveBaseResult>) istream)
  "Deserializes a message object of type '<SoftMoveBaseResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoftMoveBaseResult>)))
  "Returns string type for a message object of type '<SoftMoveBaseResult>"
  "soft_move_base/SoftMoveBaseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoftMoveBaseResult)))
  "Returns string type for a message object of type 'SoftMoveBaseResult"
  "soft_move_base/SoftMoveBaseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoftMoveBaseResult>)))
  "Returns md5sum for a message object of type '<SoftMoveBaseResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoftMoveBaseResult)))
  "Returns md5sum for a message object of type 'SoftMoveBaseResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoftMoveBaseResult>)))
  "Returns full string definition for message of type '<SoftMoveBaseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoftMoveBaseResult)))
  "Returns full string definition for message of type 'SoftMoveBaseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoftMoveBaseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoftMoveBaseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SoftMoveBaseResult
    (cl:cons ':result (result msg))
))
