/* Auto-generated by genmsg_cpp for file /u/gmanfred/ros/release/soft_controllers/pr2_soft_controller/msg/SM_TRAJ_STR_ROS.msg */
#ifndef PR2_SOFT_CONTROLLER_MESSAGE_SM_TRAJ_STR_ROS_H
#define PR2_SOFT_CONTROLLER_MESSAGE_SM_TRAJ_STR_ROS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS.h"

namespace pr2_soft_controller
{
template <class ContainerAllocator>
struct SM_TRAJ_STR_ROS_ {
  typedef SM_TRAJ_STR_ROS_<ContainerAllocator> Type;

  SM_TRAJ_STR_ROS_()
  : trajId(0)
  , nbAxis(0)
  , timePreserved(0.0)
  , qStart()
  , qGoal()
  , jmax()
  , amax()
  , vmax()
  , traj()
  {
  }

  SM_TRAJ_STR_ROS_(const ContainerAllocator& _alloc)
  : trajId(0)
  , nbAxis(0)
  , timePreserved(0.0)
  , qStart(_alloc)
  , qGoal(_alloc)
  , jmax(_alloc)
  , amax(_alloc)
  , vmax(_alloc)
  , traj(_alloc)
  {
  }

  typedef int32_t _trajId_type;
  int32_t trajId;

  typedef int32_t _nbAxis_type;
  int32_t nbAxis;

  typedef double _timePreserved_type;
  double timePreserved;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qStart_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  qStart;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qGoal_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  qGoal;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _jmax_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  jmax;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _amax_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  amax;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vmax_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  vmax;

  typedef std::vector< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> >::other >  _traj_type;
  std::vector< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> >::other >  traj;


  ROS_DEPRECATED uint32_t get_qStart_size() const { return (uint32_t)qStart.size(); }
  ROS_DEPRECATED void set_qStart_size(uint32_t size) { qStart.resize((size_t)size); }
  ROS_DEPRECATED void get_qStart_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->qStart; }
  ROS_DEPRECATED void set_qStart_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->qStart = vec; }
  ROS_DEPRECATED uint32_t get_qGoal_size() const { return (uint32_t)qGoal.size(); }
  ROS_DEPRECATED void set_qGoal_size(uint32_t size) { qGoal.resize((size_t)size); }
  ROS_DEPRECATED void get_qGoal_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->qGoal; }
  ROS_DEPRECATED void set_qGoal_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->qGoal = vec; }
  ROS_DEPRECATED uint32_t get_jmax_size() const { return (uint32_t)jmax.size(); }
  ROS_DEPRECATED void set_jmax_size(uint32_t size) { jmax.resize((size_t)size); }
  ROS_DEPRECATED void get_jmax_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->jmax; }
  ROS_DEPRECATED void set_jmax_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->jmax = vec; }
  ROS_DEPRECATED uint32_t get_amax_size() const { return (uint32_t)amax.size(); }
  ROS_DEPRECATED void set_amax_size(uint32_t size) { amax.resize((size_t)size); }
  ROS_DEPRECATED void get_amax_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->amax; }
  ROS_DEPRECATED void set_amax_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->amax = vec; }
  ROS_DEPRECATED uint32_t get_vmax_size() const { return (uint32_t)vmax.size(); }
  ROS_DEPRECATED void set_vmax_size(uint32_t size) { vmax.resize((size_t)size); }
  ROS_DEPRECATED void get_vmax_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->vmax; }
  ROS_DEPRECATED void set_vmax_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->vmax = vec; }
  ROS_DEPRECATED uint32_t get_traj_size() const { return (uint32_t)traj.size(); }
  ROS_DEPRECATED void set_traj_size(uint32_t size) { traj.resize((size_t)size); }
  ROS_DEPRECATED void get_traj_vec(std::vector< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> >::other > & vec) const { vec = this->traj; }
  ROS_DEPRECATED void set_traj_vec(const std::vector< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> >::other > & vec) { this->traj = vec; }
private:
  static const char* __s_getDataType_() { return "pr2_soft_controller/SM_TRAJ_STR_ROS"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2c772c1b72e1b0c0587ff0aecfcbcaf1"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 trajId\n\
int32 nbAxis\n\
float64 timePreserved\n\
float64[] qStart\n\
float64[] qGoal\n\
float64[] jmax\n\
float64[] amax\n\
float64[] vmax\n\
SM_TRAJ_AXIS_STR_ROS[] traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS\n\
int32 nbSeg\n\
int32 unsused\n\
SM_SEGMENT_STR_ROS[] seg\n\
\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS\n\
int32 lpId\n\
int32 unused\n\
float64 timeOnTraj\n\
float64 time\n\
float64 ic_a\n\
float64 ic_v\n\
float64 ic_x\n\
float64 jerk\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, trajId);
    ros::serialization::serialize(stream, nbAxis);
    ros::serialization::serialize(stream, timePreserved);
    ros::serialization::serialize(stream, qStart);
    ros::serialization::serialize(stream, qGoal);
    ros::serialization::serialize(stream, jmax);
    ros::serialization::serialize(stream, amax);
    ros::serialization::serialize(stream, vmax);
    ros::serialization::serialize(stream, traj);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, trajId);
    ros::serialization::deserialize(stream, nbAxis);
    ros::serialization::deserialize(stream, timePreserved);
    ros::serialization::deserialize(stream, qStart);
    ros::serialization::deserialize(stream, qGoal);
    ros::serialization::deserialize(stream, jmax);
    ros::serialization::deserialize(stream, amax);
    ros::serialization::deserialize(stream, vmax);
    ros::serialization::deserialize(stream, traj);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(trajId);
    size += ros::serialization::serializationLength(nbAxis);
    size += ros::serialization::serializationLength(timePreserved);
    size += ros::serialization::serializationLength(qStart);
    size += ros::serialization::serializationLength(qGoal);
    size += ros::serialization::serializationLength(jmax);
    size += ros::serialization::serializationLength(amax);
    size += ros::serialization::serializationLength(vmax);
    size += ros::serialization::serializationLength(traj);
    return size;
  }

  typedef boost::shared_ptr< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SM_TRAJ_STR_ROS
typedef  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<std::allocator<void> > SM_TRAJ_STR_ROS;

typedef boost::shared_ptr< ::pr2_soft_controller::SM_TRAJ_STR_ROS> SM_TRAJ_STR_ROSPtr;
typedef boost::shared_ptr< ::pr2_soft_controller::SM_TRAJ_STR_ROS const> SM_TRAJ_STR_ROSConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_soft_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c772c1b72e1b0c0587ff0aecfcbcaf1";
  }

  static const char* value(const  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2c772c1b72e1b0c0ULL;
  static const uint64_t static_value2 = 0x587ff0aecfcbcaf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_soft_controller/SM_TRAJ_STR_ROS";
  }

  static const char* value(const  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 trajId\n\
int32 nbAxis\n\
float64 timePreserved\n\
float64[] qStart\n\
float64[] qGoal\n\
float64[] jmax\n\
float64[] amax\n\
float64[] vmax\n\
SM_TRAJ_AXIS_STR_ROS[] traj\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_TRAJ_AXIS_STR_ROS\n\
int32 nbSeg\n\
int32 unsused\n\
SM_SEGMENT_STR_ROS[] seg\n\
\n\
\n\
================================================================================\n\
MSG: pr2_soft_controller/SM_SEGMENT_STR_ROS\n\
int32 lpId\n\
int32 unused\n\
float64 timeOnTraj\n\
float64 time\n\
float64 ic_a\n\
float64 ic_v\n\
float64 ic_x\n\
float64 jerk\n\
\n\
\n\
";
  }

  static const char* value(const  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.trajId);
    stream.next(m.nbAxis);
    stream.next(m.timePreserved);
    stream.next(m.qStart);
    stream.next(m.qGoal);
    stream.next(m.jmax);
    stream.next(m.amax);
    stream.next(m.vmax);
    stream.next(m.traj);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SM_TRAJ_STR_ROS_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_soft_controller::SM_TRAJ_STR_ROS_<ContainerAllocator> & v) 
  {
    s << indent << "trajId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.trajId);
    s << indent << "nbAxis: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nbAxis);
    s << indent << "timePreserved: ";
    Printer<double>::stream(s, indent + "  ", v.timePreserved);
    s << indent << "qStart[]" << std::endl;
    for (size_t i = 0; i < v.qStart.size(); ++i)
    {
      s << indent << "  qStart[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qStart[i]);
    }
    s << indent << "qGoal[]" << std::endl;
    for (size_t i = 0; i < v.qGoal.size(); ++i)
    {
      s << indent << "  qGoal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qGoal[i]);
    }
    s << indent << "jmax[]" << std::endl;
    for (size_t i = 0; i < v.jmax.size(); ++i)
    {
      s << indent << "  jmax[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jmax[i]);
    }
    s << indent << "amax[]" << std::endl;
    for (size_t i = 0; i < v.amax.size(); ++i)
    {
      s << indent << "  amax[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.amax[i]);
    }
    s << indent << "vmax[]" << std::endl;
    for (size_t i = 0; i < v.vmax.size(); ++i)
    {
      s << indent << "  vmax[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vmax[i]);
    }
    s << indent << "traj[]" << std::endl;
    for (size_t i = 0; i < v.traj.size(); ++i)
    {
      s << indent << "  traj[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pr2_soft_controller::SM_TRAJ_AXIS_STR_ROS_<ContainerAllocator> >::stream(s, indent + "    ", v.traj[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_SOFT_CONTROLLER_MESSAGE_SM_TRAJ_STR_ROS_H

